plugins {
    id 'com.android.application'
}

android {
    namespace 'com.vbdcp.attendance'
    compileSdk 35

    defaultConfig {
        applicationId 'com.vbdcp.attendance'
        minSdk 23
        targetSdk 35
        versionCode 6
        versionName '1.5'
    }

    signingConfigs {
        release {
            storeFile file("../vbdcp-release.keystore")
            storePassword project.findProperty("KEYSTORE_PASSWORD") ?: ""
            keyAlias "vbdcp"
            keyPassword project.findProperty("KEYSTORE_PASSWORD") ?: ""
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'androidx.core:core:1.13.1'
}
